"""Nookal API client package."""

from app.nookal_client.client import (
    Appointment,
    AppointmentType,
    CaseRef,
    ClassParticipant,
    ClassType,
    DocumentMeta,
    HttpNookalClient,
    Invoice,
    InvoiceEntry,
    Location,
    MockNookalClient,
    NookalClient,
    PatientExtra,
    PatientFile,
    PatientRef,
    Practitioner,
    Redemption,
    Referral,
    Referrer,
    TreatmentNote,
    UNSUPPORTED_BY_DOCUMENTED_NOOKAL_API,
    WaitingListEntry,
    build_client,
)

__all__ = [
    "Appointment",
    "AppointmentType",
    "CaseRef",
    "ClassParticipant",
    "ClassType",
    "DocumentMeta",
    "HttpNookalClient",
    "Invoice",
    "InvoiceEntry",
    "Location",
    "MockNookalClient",
    "NookalClient",
    "PatientExtra",
    "PatientFile",
    "PatientRef",
    "Practitioner",
    "Redemption",
    "Referral",
    "Referrer",
    "TreatmentNote",
    "UNSUPPORTED_BY_DOCUMENTED_NOOKAL_API",
    "WaitingListEntry",
    "build_client",
]

